using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace CoreEntity
{
    public class Movie
    {
        [Key] //to set primary key for Id 
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//autogenerated Column 
        public int Id { get; set; }
        public string Name { get; set; }
        public string MovieDesc { get; set; }
        public string MovieType { get; set; }
    }
}
